server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige toutes les routes Angular vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend Spring Boot
    location /api/ {
        proxy_pass http://backend:9096/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
